// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-jj78IPJkL3CKWle4ascyc8NIFYmfheg',
    appId: '1:1071700533173:web:daa408232e9905380483fc',
    messagingSenderId: '1071700533173',
    projectId: 'fucare-ed',
    authDomain: 'fucare-ed.firebaseapp.com',
    storageBucket: 'fucare-ed.appspot.com',
    measurementId: 'G-SN620WWJ3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB77gJARDZqypHo8jH2Myd6FceQD-tBpwk',
    appId: '1:1071700533173:android:40734d7d247b5da80483fc',
    messagingSenderId: '1071700533173',
    projectId: 'fucare-ed',
    storageBucket: 'fucare-ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtn4Ywy6-cwaoBBXmzEkvNruH-9dxD5qQ',
    appId: '1:1071700533173:ios:a3c5a5a9e31226ca0483fc',
    messagingSenderId: '1071700533173',
    projectId: 'fucare-ed',
    storageBucket: 'fucare-ed.appspot.com',
    iosClientId: '1071700533173-77jmln6fs71rr63n4qt68e31rsfpoooe.apps.googleusercontent.com',
    iosBundleId: 'com.example.noddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtn4Ywy6-cwaoBBXmzEkvNruH-9dxD5qQ',
    appId: '1:1071700533173:ios:d7f32f0e86e26cc70483fc',
    messagingSenderId: '1071700533173',
    projectId: 'fucare-ed',
    storageBucket: 'fucare-ed.appspot.com',
    iosClientId: '1071700533173-k34l0qm1c6b07rbsuceboeamp5r0sr4l.apps.googleusercontent.com',
    iosBundleId: 'com.example.noddy.RunnerTests',
  );
}
